### PR TITLE
Added and configured ESlint + Prettier + Husky

### PR DESCRIPTION
**Pull request by rachita19082**
This pull request resolves issue #14

### CODE REVIEW

**Comment by rachita19082** [comment]
@lacabra I have added and configured ESlint, Prettier and Husky. Please review and let me know if any changes are needed.

**Review by lacabra — APPROVED** [review]
Thanks @rachita19082, this looks good to me. I will wait to merge it until after #13 is merged to avoid conflicts, but consider the pull request complete.

Cc: @nathanbaleeta

**Comment by rachita19082** [comment]
@lacabra I have added github actions to enforce code style to fix issue #15 in commit 3eaff3c. Please let me know if any changes are needed.

**Comment by lacabra** [comment]
Closing in favor of #18, where the same implementation from `package.json` and `.github/workflows/main.yml` from this PR has been copied over and run the linter+prettier on the current **master** branch. Otherwise, manually resolving the conflicts in this branch as a result of merging #13 proved too tedious.

Thanks again for your contribution @rachita19082, this PR counts as if it were merged 🙏

**Pull request closed without merging**
