### PR TITLE
BLD: autosave + cookies 🍪  + legal terms

### PR DESCRIPTION
**Pull request by lacabra**
This PR implements various new features:
1. Upon clicking submit, an overlay with a spinner is displayed that disables the form, so the user cannot click any form buttons until the submission succeeds or errors out.
2. If there is an error on the submission, the router redirects to `/error` which informs the user that something went wrong, and provides instructions to email us, including the error message and a copy of the submission so that all the data that the user has entered does not get lost (see below).
3. In its simplest form, a cookie (with a life of 30 days) is used to identify and remember the user
4. Autosave functionality is implemented using a DynamoDB (NoSQL) on AWS. The `validate` (which is called every time any field changes) is partly repurposed to save the state onto the database. A `debounce` function is implemented to minimize the number of DB requests, only when the user stops typing the autosave occurs
5. When the form loads for the first time, and a cookie is found on the browser, data is loaded from the DB, and the user is notified.

In order for all this to work, be sure to install the new npm packages added on this commit: `npm i` and configure these two new variables: `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` in your `.env.local`

The following new API endpoints have been added (using dynamic routes):

* `/api/loadDB/[uuid]` - Given a `uuid` retrieves data from the DB for that user and sets initialValues in the form
* `/api/saveDB/[uuid]` - Given a `uuid` saves data to the DB for that user
* `/api/removeDB/[uuid]`- Given a `uuid` removes data from the DB for that user (upon a successful submission)

Screenshots:
1. Overlay and spinner (for testing purposes the form displayed only has 2 fields)
Screen Shot 2021-04-13 at 12 43 15 AM

2. Error page:
Screen Shot 2021-04-13 at 12 43 09 AM

5. Data loaded from DB from a previous session (notice notification at the top of the page)
Screen Shot 2021-04-13 at 12 42 58 AM

### CODE REVIEW

**Review by nathanbaleeta — CHANGES_REQUESTED** [review]
Looks good. @lacabra wouldn't it be good to notify the user before they start filling in the form that this site uses cookies?

**Comment by lacabra** [comment]
@nathanbaleeta: A new page `/legal` has been added that includes "Terms of Use", "Privacy Policy" and "Use of Cookies". Also an intro page has been added to provide an overview and inform the user of the use of cookies, as per the screenshot below. The old `index.js` has been moved to `form.js`

Screen Shot 2021-04-13 at 3 38 20 PM

**Comment by nathanbaleeta** [comment]
> @nathanbaleeta: A new page `/legal` has been added that includes "Terms of Use", "Privacy Policy" and "Use of Cookies". Also an intro page has been added to provide an overview and inform the user of the use of cookies, as per the screenshot below. The old `index.js` has been moved to `form.js`
> 
> Screen Shot 2021-04-13 at 3 38 20 PM

The page at /legal works fine. @lacabra for uniformity and providing a more user-friendly font, I would like to suggest to change the the font on  /thank-you?pr=xxx to adopt the same on /legal. Below is a sample of how it appears right now. Thanks. 

Screenshot from 2021-04-14 16-15-49

**Comment by lacabra** [comment]
@nathanbaleeta Fixed in ba4dc5e. This became a rabbit hole. Also fixed [an issue](https://stackoverflow.com/questions/60060544/page-refresh-break-styles-on-nextjs-production-app) with NextJS breaking the MUI theme. See [this repo](https://github.com/mui-org/material-ui/tree/next/examples/nextjs) for reference.

Standardized all the pages, extracted the theme to its own file, and imported it globally. Merged the contents of `styles/global.css` into the MUI theme.

Reference screenshots:

Screen Shot 2021-04-14 at 10 41 33 AM

Screen Shot 2021-04-14 at 10 41 52 AM

Screen Shot 2021-04-14 at 10 41 17 AM

**Comment by nathanbaleeta** [comment]
> @nathanbaleeta Fixed in [ba4dc5e](https://github.com/lacabra/submission-digitalpublicgoods/commit/ba4dc5eb09f7134fdb2ab9487dea69511a51a75f). This became a rabbit hole. Also fixed [an issue](https://stackoverflow.com/questions/60060544/page-refresh-break-styles-on-nextjs-production-app) with NextJS breaking the MUI theme. See [this repo](https://github.com/mui-org/material-ui/tree/next/examples/nextjs) for reference.
> 
> Standardized all the pages, extracted the theme to its own file, and imported it globally. Merged the contents of `styles/global.css` into the MUI theme.
> 
> Reference screenshots:
> 
> Screen Shot 2021-04-14 at 10 41 33 AM
> 
> Screen Shot 2021-04-14 at 10 41 52 AM
> 
> Screen Shot 2021-04-14 at 10 41 17 AM

Thanks @lacabra this looks good and works fine! Now ready for merging.

**Pull request merged**
