### PR TITLE
PATCH: Update PII question description

### PR DESCRIPTION
**Pull request by nathanfletcher**
This PR:

- Addresses and updates the PII question as mentioned in #46

### CODE REVIEW

**Comment by lacabra** [comment]
Waiting to resolve unicef/publicgoods-candidates#669

**Comment by nathanfletcher** [comment]
@lacabra [unicef/publicgoods-candidates#669](https://github.com/unicef/publicgoods-candidates/pull/669) has been resolved now. The PR has been closed. Pending review of this one.

**Comment by lacabra** [comment]
I have the same comment I made there: no single entry in the schema should have two "if yes - then question". Each such statement should be its own entry.

**Comment by lacabra** [comment]
The underlying issue has been resolved in #60. This PR is no longer valid.

**Pull request closed without merging**
