### PR TITLE
Reset form fields after clicking submit button

### PR DESCRIPTION
**Pull request by nathanbaleeta**
Reset form fields after clicking submit button.

### CODE REVIEW

**Review by lacabra — CHANGES_REQUESTED** [review]
Thanks @nathanbaleeta 🙏

I would like a new page to get displayed after the user submits, and the PR is opened. Can you modify the flow so that the user lands in a new page that says:

- Thank you
- The form has been submitted successfully
- Provides a link to the PR that has been opened
- and includes a button to start a new submission

Thanks again

**Review by lacabra — APPROVED** [review]
@nathanbaleeta This was really easy once you realize we're working on the NextJS environment, so when we need redirects, we have to use [NextJS router](https://nextjs.org/docs/api-reference/next/router). What you were pursuing initially turned out to be a dead end for me. I have included a number of other changes and clean up other things, but the gist of my changes can be found on [this line](https://github.com/lacabra/submission-digitalpublicgoods/blob/95d00d9d9365bee6597b34070ba1db13670fc509/pages/index.js#L204).

**Comment by lacabra** [comment]
I have also revamped the `/thank-you` page, and clearing the form comes for free when you navigate away from it, as expected.

Kindly note the renaming of two environment variables in 5c07634 to make them visible client side.

**Comment by nathanbaleeta** [comment]
@lacabra added a line that appends a newline character to end of file to prevent the pull request from breaking when the Github CI runs eventually.

**Pull request merged**
