### PR TITLE
Replaced single page form with multi page one for submission

### PR DESCRIPTION
**Pull request by nathanbaleeta**
Replaced single page form with multi page one for submission. However a minor bug was introduced causing the SDG subform to shift to top of page and persists even on navigating to page 2.

### CODE REVIEW

**Comment by lacabra** [comment]
@nathanbaleeta The issue you were experiencing has been fixed in bb0772b.

The explanation is as follows: the code in lines [534-567](https://github.com/lacabra/submission-digitalpublicgoods/blob/bb0772b2beb2a963300358ae8d664b6a0e205a7a/schemas/schema.js#L534) dynamically generates the portion of the schema needed for each of the 17 goals, and optimizes the coding by looping through 17 items that are essentially the same, instead of us having to type all these manually.

In order to accomplish this, the crux is in L536 and L537 where the code locates the position of the element that contains the `SDGs` and appends the new subform for each SDG right afterwards, by way of splicing the `fields` array.

Since you modified the structure of the dictionary holding the schema, you have to adjust the looking for the right position for that `SDGs` element accordingly: the first `fields[0]` accounts for the `wizard` component you added, while the second `fields[0]` accounts for the `step-1` component. Inside there is where we find the previous `fields` array where we perform the `findIndex()` operation like before.

**Comment by lacabra** [comment]
@nathanbaleeta You may have noticed that in your branch, there was an extra `Submit` button that was appearing in the multipage form, in addition to the `Continue` in the first page, and the `Submit` on the second page, as illustrated in the screenshot below (crossed out):
Screen Shot 2021-01-27 at 5 04 42 PM

This has been fixed in b70303f

**Comment by nathanbaleeta** [comment]
> @nathanbaleeta The issue you were experiencing has been fixed in [bb0772b](https://github.com/lacabra/submission-digitalpublicgoods/commit/bb0772b2beb2a963300358ae8d664b6a0e205a7a).
> 
> The explanation is as follows: the code in lines [534-567](https://github.com/lacabra/submission-digitalpublicgoods/blob/bb0772b2beb2a963300358ae8d664b6a0e205a7a/schemas/schema.js#L534) dynamically generates the portion of the schema needed for each of the 17 goals, and optimizes the coding by looping through 17 items that are essentially the same, instead of us having to type all these manually.
> 
> In order to accomplish this, the crux is in L536 and L537 where the code locates the position of the element that contains the `SDGs` and appends the new subform for each SDG right afterwards, by way of splicing the `fields` array.
> 
> Since you modified the structure of the dictionary holding the schema, you have to adjust the looking for the right position for that `SDGs` element accordingly: the first `fields[0]` accounts for the `wizard` component you added, while the second `fields[0]` accounts for the `step-1` component. Inside there is where we find the previous `fields` array where we perform the `findIndex()` operation like before.

@lacabra the explanation is quite clear and helpful. Would you be able to share any additional documentation you used to resolve this issue for future reference. Thanks.

**Comment by lacabra** [comment]
> @lacabra the explanation is quite clear and helpful. Would you be able to share any additional documentation you used to resolve this issue for future reference. Thanks.

@nathanbaleeta I don't have much else to share beyond you already know, I'm afraid. I based my knowledge here from the documentation of [Data Driven Forms](https://data-driven-forms.org/) and general knowledge of Javascript, but will let you know if something else comes to mind.

**Pull request merged**
